// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaiMGIwVP0IXXO4W-u0GDO9ss3cB2Lxic',
    appId: '1:194902792860:web:73c89d00aae95303936b59',
    messagingSenderId: '194902792860',
    projectId: 'chat-app-2da58',
    authDomain: 'chat-app-2da58.firebaseapp.com',
    storageBucket: 'chat-app-2da58.firebasestorage.app',
    measurementId: 'G-JGP54N2KX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0ToN-D7i6URqutKdTv79SfZavJ-iVa1s',
    appId: '1:194902792860:android:c1ecbd8e67c17231936b59',
    messagingSenderId: '194902792860',
    projectId: 'chat-app-2da58',
    storageBucket: 'chat-app-2da58.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAarih-57-BOzH5-roKJxVx_gbzEcCAiWQ',
    appId: '1:194902792860:ios:0878f281620ef172936b59',
    messagingSenderId: '194902792860',
    projectId: 'chat-app-2da58',
    storageBucket: 'chat-app-2da58.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
}
